name: Docker build test

on: push

jobs:
  build-and-push-docker-images:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the private Ops repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          submodules: "recursive"

      - name: Log in to Docker Hub

        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        # with:
        #   version: "lab:latest"
        #   driver: cloud
        #   endpoint: "lunary/lunary"

      - name: Build test
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./ops/backend.Dockerfile
          push: true
          tags: |
            lunary/backend:test
          platforms: linux/amd64,linux/arm64
