name: Deploy on Release

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: namespace-profile-fast
    steps:
      - name: Check out the private Ops repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: "recursive"

      - name: Get release version
        id: get_version
        run: echo "::set-output name=version::${GITHUB_REF#refs/tags/}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to private Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Pull and redeploy backend
        run: |
          docker pull lunary/backend:${{ steps.get_version.outputs.version }}
          docker stop backend
          docker rm backend
          docker run -d --name backend lunary/backend:${{ steps.get_version.outputs.version }}

      - name: Pull and redeploy frontend
        run: |
          docker pull lunary/frontend:${{ steps.get_version.outputs.version }}
          docker stop frontend
          docker rm frontend
          docker run -d --name frontend lunary/frontend:${{ steps.get_version.outputs.version }}

      - name: Pull and redeploy radar
        run: |
          docker pull lunary/radar:${{ steps.get_version.outputs.version }}
          docker stop radar
          docker rm radar
          docker run -d --name radar lunary/radar:${{ steps.get_version.outputs.version }}

      - name: Pull and redeploy ml
        run: |
          docker pull lunary/ml:${{ steps.get_version.outputs.version }}
          docker stop ml
          docker rm ml
          docker run -d --name ml lunary/ml:${{ steps.get_version.outputs.version }}
